# Generated by Django 6.0.3 on 2026-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
